// <auto-generated />
namespace thewall9.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcurrencyinorders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcurrencyinorders));
        
        string IMigrationMetadata.Id
        {
            get { return "201504022103525_add-currency-in-orders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
