// <auto-generated />
namespace thewall9.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addecommerce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addecommerce));
        
        string IMigrationMetadata.Id
        {
            get { return "201503201916341_add-e-commerce"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
